### ISSUE TITLE
Reboot module hangs when run from a Linux host

### ISSUE THREAD

**Issue by BladesOfSteele** [IBM/ansible-power-aix#666]
When running ibm.power_aix.reboot from a Linux host, the module executes the reboot, but hangs and never validates the reboot completed.

For example, from a Ubuntu or RHEL host:
```
[msteele@Moebius-Orion tmp]$ ansible test2 -m ibm.power_aix.reboot -vvv -i inventory.ini  -u root
ansible [core 2.16.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/msteele/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/msteele/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/msteele/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/msteele/.local/bin/ansible
  python version = 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /home/msteele/tmp/inventory.ini as it did not pass its verify_file() method
script declined parsing /home/msteele/tmp/inventory.ini as it did not pass its verify_file() method
auto declined parsing /home/msteele/tmp/inventory.ini as it did not pass its verify_file() method
yaml declined parsing /home/msteele/tmp/inventory.ini as it did not pass its verify_file() method
Parsed /home/msteele/tmp/inventory.ini inventory source with ini plugin
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
System reboot process has started....
<192.168.65.65> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.65.65> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o 'ControlPath="/home/msteele/.ansible/cp/0bbcdfb191"' -tt 192.168.65.65 '/bin/sh -c '"'"'shutdown -r && sleep 0'"'"''
```
This command then just hangs until ctrl-c'ed.

From an AIX host, it runs fine:
```
aixtest01:/home/root/ansible# ansible test2 -m ibm.power_aix.reboot -vvv
ansible [core 2.15.13]
  config file = /home/root/ansible/ansible.cfg
  configured module search path = ['/home/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/freeware/lib/python3.9/site-packages/ansible
  ansible collection location = /home/root/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/freeware/bin/ansible
  python version = 3.9.20 (main, Sep 27 2024, 03:16:26) [GCC 10.3.0] (/opt/freeware/bin/python3)
  jinja version = 3.1.6
  libyaml = False
Using /home/root/ansible/ansible.cfg as config file
host_list declined parsing /home/root/ansible/inventory.ini as it did not pass its verify_file() method
auto declined parsing /home/root/ansible/inventory.ini as it did not pass its verify_file() method
yaml declined parsing /home/root/ansible/inventory.ini as it did not pass its verify_file() method
Parsed /home/root/ansible/inventory.ini inventory source with ini plugin
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
System reboot process has started....
<192.168.65.65> ESTABLISH SSH CONNECTION FOR USER: None
<192.168.65.65> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o 'ControlPath="/home/root/.ansible/cp/bb6b2048a0"' -tt 192.168.65.65 '/bin/sh -c '"'"'shutdown -r && sleep 0'"'"''
<192.168.65.65> (255, b'\r\nSHUTDOWN PROGRAM\r\nMon Jun  9 10:38:56 PDT 2025\r\n\r\r\r\n\r\r\n\x07Broadcast message from root@aix_test (tty) at 10:38:56 ... \r\r\r\n\r\r\nshutdown: PLEASE LOG OFF NOW !!!\r\r\nAll processes will be killed in 1 minute.\r\r\n\r\r\n\r\r\r\n\r\r\n\x07Broadcast message from root@aix_test (pts/0) at 10:39:29 ... \r\r\r\n\r\r\nshutdown: THE SYSTEM IS BEING SHUT DOWN NOW\r\r\n\r\r\n', b'Shared connection to 192.168.65.65 closed.\r\n')
AnsibleConnectionFailure has been caught and handled
Validating reboot....
<192.168.65.65> ESTABLISH SSH CONNECTION FOR USER: None
<192.168.65.65> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o 'ControlPath="/home/root/.ansible/cp/bb6b2048a0"' -tt 192.168.65.65 '/bin/sh -c '"'"'whoami && sleep 0'"'"''
<192.168.65.65> (255, b'', b'ssh: connect to host 192.168.65.65 port 22: Connection refused\r\n')
sending connection check: [b'ssh', b'-C', b'-o', b'ControlMaster=auto', b'-o', b'ControlPersist=60s', b'-o', b'KbdInteractiveAuthentication=no', b'-o', b'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', b'-o', b'PasswordAuthentication=no', b'-o', b'ConnectTimeout=10', b'-o', b'ControlPath="/home/root/.ansible/cp/bb6b2048a0"', b'-O', b'check', b'192.168.65.65']
No connection to reset: Control socket connect(/home/root/.ansible/cp/bb6b2048a0): No such file or directory
<192.168.65.65> ESTABLISH SSH CONNECTION FOR USER: None
...
<192.168.65.65> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o 'ControlPath="/home/root/.ansible/cp/bb6b2048a0"' -tt 192.168.65.65 '/bin/sh -c '"'"'whoami && sleep 0'"'"''
<192.168.65.65> (255, b'', b'ssh: connect to host 192.168.65.65 port 22: Connection refused\r\n')
sending connection check: [b'ssh', b'-C', b'-o', b'ControlMaster=auto', b'-o', b'ControlPersist=60s', b'-o', b'KbdInteractiveAuthentication=no', b'-o', b'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', b'-o', b'PasswordAuthentication=no', b'-o', b'ConnectTimeout=10', b'-o', b'ControlPath="/home/root/.ansible/cp/bb6b2048a0"', b'-O', b'check', b'192.168.65.65']
No connection to reset: Control socket connect(/home/root/.ansible/cp/bb6b2048a0): No such file or directory
<192.168.65.65> ESTABLISH SSH CONNECTION FOR USER: None
<192.168.65.65> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o 'ControlPath="/home/root/.ansible/cp/bb6b2048a0"' -tt 192.168.65.65 '/bin/sh -c '"'"'whoami && sleep 0'"'"''
<192.168.65.65> (255, b'', b'ssh: connect to host 192.168.65.65 port 22: Connection refused\r\n')
sending connection check: [b'ssh', b'-C', b'-o', b'ControlMaster=auto', b'-o', b'ControlPersist=60s', b'-o', b'KbdInteractiveAuthentication=no', b'-o', b'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', b'-o', b'PasswordAuthentication=no', b'-o', b'ConnectTimeout=10', b'-o', b'ControlPath="/home/root/.ansible/cp/bb6b2048a0"', b'-O', b'check', b'192.168.65.65']
No connection to reset: Control socket connect(/home/root/.ansible/cp/bb6b2048a0): No such file or directory
<192.168.65.65> ESTABLISH SSH CONNECTION FOR USER: None
<192.168.65.65> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o 'ControlPath="/home/root/.ansible/cp/bb6b2048a0"' -tt 192.168.65.65 '/bin/sh -c '"'"'whoami && sleep 0'"'"''
<192.168.65.65> (0, b'root\r\n', b'Shared connection to 192.168.65.65 closed.\r\n')
192.168.65.65 | CHANGED => {
    "changed": true,
    "elapsed": "174 sec",
    "msg": "System has been rebooted SUCCESSFULLY",
    "rebooted": true
}
aixtest01:/home/root/ansible#
```

I'd expect the behavior to be the same.

AIX system to be rebooted: 7300-01-03-2346
Ubuntu Linux that fails: 22.04
RHEL version that fails: 9.6
AIX system that runs module successfully: 7.2.0.0

**Comment by BladesOfSteele** [comment]
Forgot to add, ansible.cfg is configured as per documentation
msteele@Moebius-Orion tmp]$ ansible-config  view
[𝚜𝚜𝚑_𝚌𝚘𝚗𝚗𝚎𝚌𝚝𝚒𝚘𝚗]
𝚜𝚜𝚑_𝚊𝚛𝚐𝚜 = -𝚘 𝙵𝚘𝚛𝚠𝚊𝚛𝚍𝙰𝚐𝚎𝚗𝚝=𝚢𝚎𝚜 -𝚘 𝙲𝚘𝚗𝚝𝚛𝚘𝚕𝙿𝚎𝚛𝚜𝚒𝚜𝚝=𝟹𝟶𝚖 -𝚘 𝚂𝚎𝚛𝚟𝚎𝚛𝙰𝚕𝚒𝚟𝚎𝙸𝚗𝚝𝚎𝚛𝚟𝚊𝚕=𝟺𝟻 -𝚘 𝚂𝚎𝚛𝚟𝚎𝚛𝙰𝚕𝚒𝚟𝚎𝙲𝚘𝚞𝚗𝚝𝙼𝚊𝚡=𝟷𝟶

**Comment by nitismis** [comment]
Thanks for the details. We will look into this.

**Comment by schamola** [comment]
Hi @BladesOfSteele 
We've fixed the issue and it is working in our environment.
FIX PR - #680

Can you please verify ??

**Comment by schamola** [comment]
Hi @BladesOfSteele 
Can you please confirm ?

**Comment by BladesOfSteele** [comment]
sorry for the delay, I still see the same issue.

```
[msteele@Moebius-Orion pge (main *)]$ 
[msteele@Moebius-Orion pge (main *)]$ ansible-galaxy collection list | grep ibm.power_aix
ibm.power_aix                            2.1.1  
[msteele@Moebius-Orion pge (main *)]$ ansible aix_test -m ibm.power_aix.reboot -i inventory.ini -l aix_test -u root -vvv
ansible [core 2.16.6]
  config file = /home/msteele/repos/pge/pge/ansible.cfg
  configured module search path = ['/home/msteele/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/msteele/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/msteele/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/msteele/.local/bin/ansible
  python version = 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True
Using /home/msteele/repos/pge/pge/ansible.cfg as config file
host_list declined parsing /home/msteele/repos/pge/pge/inventory.ini as it did not pass its verify_file() method
script declined parsing /home/msteele/repos/pge/pge/inventory.ini as it did not pass its verify_file() method
auto declined parsing /home/msteele/repos/pge/pge/inventory.ini as it did not pass its verify_file() method
yaml declined parsing /home/msteele/repos/pge/pge/inventory.ini as it did not pass its verify_file() method
Parsed /home/msteele/repos/pge/pge/inventory.ini inventory source with ini plugin
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
System reboot process has started....
<192.168.65.65> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.65.65> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o 'ControlPath="/home/msteele/.ansible/cp/0bbcdfb191"' -tt 192.168.65.65 '/bin/sh -c '"'"'shutdown -r && sleep 0'"'"''
^C [ERROR]: User interrupted execution
[msteele@Moebius-Orion pge (main *)]$ ssh root@aix_test uptime
  08:57AM   up 3 mins,  0 users,  load average: 0.72, 0.53, 0.23
[msteele@Moebius-Orion pge (main *)]$ 
```

**Comment by schamola** [comment]
Hi @BladesOfSteele 

The fix is not available on Galaxy yet so you will have to manually replace `/plugins/action/reboot.py` file present on your system with the new one present [here](https://github.com/IBM/ansible-power-aix/blob/dev-collection/plugins/action/reboot.py)

Can you please confirm if the issue still persists after this ?

**Comment by BladesOfSteele** [comment]
I replaced reboot.py and still seeing the same issue. To make absolutely sure, I added a ! to the end of the _System reboot process has started_ line to validate I'm running the new version of reboot.py.

```
[msteele@Moebius-Orion pge (main)]$ ansible aix_test -m ibm.power_aix.reboot -i inventory.ini -l aix_test -u root -vvv
ansible [core 2.16.6]
  config file = /home/msteele/repos/pge/pge/ansible.cfg
  configured module search path = ['/home/msteele/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/msteele/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/msteele/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/msteele/.local/bin/ansible
  python version = 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True
Using /home/msteele/repos/pge/pge/ansible.cfg as config file
host_list declined parsing /home/msteele/repos/pge/pge/inventory.ini as it did not pass its verify_file() method
script declined parsing /home/msteele/repos/pge/pge/inventory.ini as it did not pass its verify_file() method
auto declined parsing /home/msteele/repos/pge/pge/inventory.ini as it did not pass its verify_file() method
yaml declined parsing /home/msteele/repos/pge/pge/inventory.ini as it did not pass its verify_file() method
Parsed /home/msteele/repos/pge/pge/inventory.ini inventory source with ini plugin
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
System reboot process has started....!
<192.168.65.65> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.65.65> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o 'ControlPath="/home/msteele/.ansible/cp/0bbcdfb191"' -tt 192.168.65.65 '/bin/sh -c '"'"'shutdown -r && sleep 0'"'"''
^C [ERROR]: User interrupted execution
```

**Comment by schamola** [comment]
Hi @BladesOfSteele 
One more thing that I can see is that you are not using the recommended SSH arguments.

From your output's 2nd last line: `-o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10.....`

Recommended: `ssh_args = -o ForwardAgent=yes -o ControlPersist=30m -o ServerAliveInterval=45 -o ServerAliveCountMax=10`


Maybe this could be the issue...  Can you please verify ?
Let us know if the issue still persists

**Comment by BladesOfSteele** [comment]
I've been running this from Ubuntu VM or Ubuntu WSL instances, all of them have the same default settings:
```
$ ssh -G randomhost | egrep -i "ForwardAgent|ControlPersist|ServerAliveInterval|ServerAliveCountMax"
serveralivecountmax 3
serveraliveinterval 0
forwardagent no
controlpersist no
```

However, using the recommended parameters work.
```
$ ansible aix_test -m ibm.power_aix.reboot -i inventory.ini -l aix_test -u root -vvv --ssh-extra-args " -o ForwardAgent=yes -o ControlPersist=30m -o ServerAliveInterval=45 -o ServerAliveCountMax=10"
ansible [core 2.16.6]
  config file = /home/msteele/repos/pge/pge/ansible.cfg
  configured module search path = ['/home/msteele/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/msteele/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/msteele/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/msteele/.local/bin/ansible
  python version = 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True
Using /home/msteele/repos/pge/pge/ansible.cfg as config file
host_list declined parsing /home/msteele/repos/pge/pge/inventory.ini as it did not pass its verify_file() method
script declined parsing /home/msteele/repos/pge/pge/inventory.ini as it did not pass its verify_file() method
auto declined parsing /home/msteele/repos/pge/pge/inventory.ini as it did not pass its verify_file() method
yaml declined parsing /home/msteele/repos/pge/pge/inventory.ini as it did not pass its verify_file() method
Parsed /home/msteele/repos/pge/pge/inventory.ini inventory source with ini plugin
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
System reboot process has started....!
<192.168.65.65> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.65.65> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ForwardAgent=yes -o ControlPersist=30m -o ServerAliveInterval=45 -o ServerAliveCountMax=10 -o 'ControlPath="/home/msteele/.ansible/cp/0bbcdfb191"' -tt 192.168.65.65 '/bin/sh -c '"'"'shutdown -r && sleep 0'"'"''
<192.168.65.65> (255, b"\r\nSHUTDOWN PROGRAM\r\nWed Aug 20 07:05:31 PDT 2025\r\n\r\r\r\n\r\r\n\x07Broadcast message from root@aix_test (tty) at 07:05:31 ... \r\r\r\n\r\r\nshutdown: PLEASE LOG OFF NOW !!!\r\r\nAll processes will be killed in 1 minute.\r\r\n\r\r\n\r\r\r\n\r\r\n\x07Broadcast message from root@aix_test (pts/0) at 07:06:31 ... \r\r\r\n\r\r\nshutdown: THE SYSTEM IS BEING SHUT DOWN NOW\r\r\n\r\r\nclissuepage: clissuepage exited with the return code = 0\r\n# ct_clusterinfo - ct_caa_get_cluster_info() returns -4\r\n0513-044 The sshd Subsystem was requested to stop.\r\n\r\nWait for 'Rebooting...' before stopping. \r\nError reporting has stopped.\r\nAdvanced Accounting has stopped...\r\nProcess accounting has stopped.\r\nnfs_clean: Stopping NFS/NIS Daemons\r\n0513-004 The Subsystem or Group, nfsd, is currently inoperative.\r\n0513-004 The Subsystem or Group, biod, is currently inoperative.\r\n0513-004 The Subsystem or Group, rpc.lockd, is currently inoperative.\r\n0513-004 The Subsystem or Group, rpc.statd, is currently inoperative.\r\n0513-004 The Subsystem or Group, gssd, is currently inoperative.\r\n0513-004 The Subsystem or Group, nfsrgyd, is currently inoperative.\r\n0513-004 The Subsystem or Group, rpc.mountd, is currently inoperative.\r\n0513-004 The Subsystem or Group, ypbind, is currently inoperative.\r\n0513-044 The xntpd Subsystem was requested to stop.\r\n0513-044 The hostmibd Subsystem was requested to stop.\r\n0513-044 The snmpmibd Subsystem was requested to stop.\r\n0513-044 The aixmibd Subsystem was requested to stop.\r\n0513-044 The nimsh Subsystem was requested to stop.\r\n0513-044 The aso Subsystem was requested to stop.\r\n0513-044 The qdaemon Subsystem was requested to stop.\r\n0513-044 The writesrv Subsystem was requested to stop.\r\n0513-044 The clcomd Subsystem was requested to stop.\r\n0513-044 The pfcdaemon Subsystem was requested to stop.\r\n0513-044 The netcd Subsystem was requested to stop.\r\n0513-044 The clconfd Subsystem was requested to stop.\r\n0513-044 The clstrmgrES Subsystem was requested to stop.\r\n0513-044 The clxd Subsystem was requested to stop.\r\nAll processes currently running will now be killed...\r\nUnmounting the file systems...\r\n/usr/sbin/shutdown[1376]: echo: write to 1 failed [There is an input or output error.]\r\n/usr/sbin/shutdown[1387]: echo: write to 1 failed [There is an input or output error.]\r\n", b'Shared connection to 192.168.65.65 closed.\r\n')
AnsibleConnectionFailure has been caught and handled
Validating reboot....
<192.168.65.65> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.65.65> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ForwardAgent=yes -o ControlPersist=30m -o ServerAliveInterval=45 -o ServerAliveCountMax=10 -o 'ControlPath="/home/msteele/.ansible/cp/0bbcdfb191"' -tt 192.168.65.65 '/bin/sh -c '"'"'whoami && sleep 0'"'"''
<192.168.65.65> (255, b'', b'ssh: connect to host 192.168.65.65 port 22: Connection refused\r\n')
sending connection check: [b'ssh', b'-C', b'-o', b'ControlMaster=auto', b'-o', b'ControlPersist=60s', b'-o', b'KbdInteractiveAuthentication=no', b'-o', b'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', b'-o', b'PasswordAuthentication=no', b'-o', b'User="root"', b'-o', b'ConnectTimeout=10', b'-o', b'ForwardAgent=yes', b'-o', b'ControlPersist=30m', b'-o', b'ServerAliveInterval=45', b'-o', b'ServerAliveCountMax=10', b'-o', b'ControlPath="/home/msteele/.ansible/cp/0bbcdfb191"', b'-O', b'check', b'192.168.65.65']
No connection to reset: Control socket connect(/home/msteele/.ansible/cp/0bbcdfb191): No such file or directory
<192.168.65.65> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.65.65> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ForwardAgent=yes -o ControlPersist=30m -o ServerAliveInterval=45 -o ServerAliveCountMax=10 -o 'ControlPath="/home/msteele/.ansible/cp/0bbcdfb191"' -tt 192.168.65.65 '/bin/sh -c '"'"'whoami && sleep 0'"'"''
<192.168.65.65> (255, b'', b'ssh: connect to host 192.168.65.65 port 22: Connection refused\r\n')
sending connection check: [b'ssh', b'-C', b'-o', b'ControlMaster=auto', b'-o', b'ControlPersist=60s', b'-o', b'KbdInteractiveAuthentication=no', b'-o', b'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', b'-o', b'PasswordAuthentication=no', b'-o', b'User="root"', b'-o', b'ConnectTimeout=10', b'-o', b'ForwardAgent=yes', b'-o', b'ControlPersist=30m', b'-o', b'ServerAliveInterval=45', b'-o', b'ServerAliveCountMax=10', b'-o', b'ControlPath="/home/msteele/.ansible/cp/0bbcdfb191"', b'-O', b'check', b'192.168.65.65']
No connection to reset: Control socket connect(/home/msteele/.ansible/cp/0bbcdfb191): No such file or directory
<192.168.65.65> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.65.65> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ForwardAgent=yes -o ControlPersist=30m -o ServerAliveInterval=45 -o ServerAliveCountMax=10 -o 'ControlPath="/home/msteele/.ansible/cp/0bbcdfb191"' -tt 192.168.65.65 '/bin/sh -c '"'"'whoami && sleep 0'"'"''
<192.168.65.65> (0, b'root\r\n', b'Shared connection to 192.168.65.65 closed.\r\n')
192.168.65.65 | CHANGED => {
    "changed": true,
    "elapsed": "231 sec",
    "msg": "System has been rebooted SUCCESSFULLY",
    "rebooted": true
}
```

Not sure what the correct response is, since these ssh settings are Ubuntu defaults, at least from what I can see.

**Comment by schamola** [comment]
@BladesOfSteele 
For reboot action to work, SSH arguments for Ansible need to be set in this particular way only.
Otherwise, the SSH connection breaks and it keeps on polling until timeout happens, ending with a failure message.
